### ISSUE TITLE
Plugin ownership change?

### ISSUE THREAD

**Issue by farinspace** [JoryHogeveen/widget-css-classes#1]
Any explanation as to why plugin ownership has changed from "C.M. Kendrick" to "Jory Hogeveen"?

Is the plugin going to head in a new direction?

Is it just a new maintainer thing?

**Comment by JoryHogeveen** [comment]
She decided to transfer ownership of this plugin to me as she was inactive in it's maintenance and development for the last years and isn't intending to continue with the plugin.
Because of this I decided to move the main repo to my fork to make it easier for me to continue maintenance and development.

Cheers! Jory
